#!/usr/bin/env bash
#
# zwatch -- every generated block in the documentation, regenerated and
# compared.
#
# A block between `<!-- BEGIN GENERATED <command> -->` and
# `<!-- END GENERATED -->` must equal that command's output. The marker
# names the generator, so a reader can rerun it.
#
# Usage:
#   ci/check-docs.sh           # compare, fail on any difference
#   ci/check-docs.sh --write   # rewrite the blocks from their generators

set -uo pipefail
cd "$(dirname "$0")/.."

exec python3 - "${1:-}" <<'PY'
import difflib, pathlib, re, subprocess, sys

write = sys.argv[1] == "--write"
block = re.compile(
    r"(?P<open><!-- BEGIN GENERATED (?P<cmd>[^>]+?) -->\n)"
    r"(?P<body>.*?)"
    r"(?P<close><!-- END GENERATED -->)",
    re.S,
)
failures = 0

for doc in sorted(pathlib.Path(".").glob("*.md")):
    text = doc.read_text(encoding="utf-8")
    out, end = [], 0
    for m in block.finditer(text):
        cmd = m.group("cmd").strip()
        run = subprocess.run(["bash", "-c", cmd], capture_output=True, text=True)
        if run.returncode != 0:
            print("%s: generator failed: %s\n%s" % (doc, cmd, run.stderr.strip()))
            failures += 1
            continue
        want = run.stdout.replace("\r\n", "\n")
        if not want.endswith("\n"):
            want += "\n"
        if m.group("body") != want:
            failures += 1
            print("%s: the block generated by `%s` is stale:" % (doc, cmd))
            for line in difflib.unified_diff(
                m.group("body").splitlines(True), want.splitlines(True),
                fromfile="in the document", tofile=cmd, n=1,
            ):
                print("  " + line.rstrip("\n"))
        out.append(text[end:m.start()])
        out.append(m.group("open") + want + m.group("close"))
        end = m.end()
    if write and out:
        out.append(text[end:])
        # open() rather than Path.write_text: the newline keyword reached
        # it only in Python 3.13, and hosted runners are older.
        with open(doc, "w", encoding="utf-8", newline="\n") as f:
            f.write("".join(out))

sys.exit(1 if failures else 0)
PY
